---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint -c .ansible-lint . -v
platforms:
  - name: test-docker-centos7-openjdk
    image: leandelivery/docker-systemd:centos7
    privileged: true
    pre_build_image: true
    groups:
      - rhel_family
  - name: test-docker-ubuntu1804-openjdk
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    pre_build_image: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    verify: ../resources/tests/verify.yml
  lint: |
    set -e
    yamllint -c .yamllint .
scenario:
  name: default
verifier:
  name: ansible
  lint: |
    set -e
    yamllint -c .yamllint .
