---
name: Lint

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .
          yamllint_config_filepath: .yamllint
          yamllint_format: colored
          yamllint_strict: false #TODO: think about it (true/false)

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout ansible lint rules
        uses: actions/checkout@v2
        with:
          repository: lean-delivery/ansible-lint-rules
          path: ansible-lint-rules


      - name: Ansible Lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: .
          args: "-c .ansible-lint"

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    needs:
      - yamllint
      - ansible-lint
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          # clean: false

      # - name: Checkout ansible lint rules
      #   uses: actions/checkout@v2
      #   with:
      #     repository: lean-delivery/ansible-lint-rules
      #     path: ${{ github.repository }}/ansible-lint-rules
      #     clean: false

      - name: Molecule
        uses: gofrolist/molecule-action@master
        with:
          molecule_options: --debug
          molecule_command: test
          molecule_args: --scenario-name default
