---
name: Lint

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: .
          yamllint_config_filepath: .yamllint
          yamllint_format: colored
          yamllint_strict: true

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   clean: false

      - name: Checkout lint rules
        uses: actions/checkout@v2
        with:
          repository: lean-delivery/ansible-lint-rules
          path: ansible-lint-rules
          # clean: false


      - name: Ansible Lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: .
          args: "-c .ansible-lint"
